export const GITHUB_REPO_URL = "https://github.com/12ian34/loclocloc";

export const LONDON_CENTER = [51.505, -0.09];
export const LONDON_ZOOM = 11;

export const POINT_LAYERS = [
  { id: "tube", name: "Tube & Rail", file: "/data/tube-rail.geojson", color: "#003688", emoji: "🚇" },
  { id: "waitrose", name: "Waitrose", file: "/data/waitrose.geojson", color: "#4a7c59", emoji: "🛒" },
  { id: "supermarkets", name: "Supermarkets", file: "/data/supermarkets.geojson", color: "#0d9488", emoji: "🏪" },
  { id: "coffee", name: "Coffee Shops", file: "/data/coffee.geojson", color: "#6f4e37", emoji: "☕" },
  { id: "libraries", name: "Libraries", file: "/data/libraries.geojson", color: "#6366f1", emoji: "📚" },
  { id: "pubs", name: "Pubs", file: "/data/pubs.geojson", color: "#c9a227", emoji: "🍺" },
  { id: "parks", name: "Parks", file: "/data/parks.geojson", color: "#2d8c3c", emoji: "🌳" },
  { id: "yoga", name: "Yoga Studios", file: "/data/yoga.geojson", color: "#c06cba", emoji: "🧘" },
  { id: "gyms", name: "Gyms", file: "/data/gyms.geojson", color: "#e05555", emoji: "💪" },
  { id: "cinemas", name: "Cinemas", file: "/data/cinemas.geojson", color: "#8b5cf6", emoji: "🎬" },
  { id: "bike-parking", name: "Bike Parking", file: "/data/bike-parking.geojson", color: "#0ea5e9", emoji: "🚲" },
  { id: "betting", name: "Betting Shops", file: "/data/betting.geojson", color: "#ef4444", emoji: "🎰" },
  { id: "restaurants", name: "Restaurants", file: "/data/restaurants.geojson", color: "#f97316", emoji: "🍽️" },
  { id: "gp-surgeries", name: "GP Surgeries", file: "/data/gp-surgeries.geojson", color: "#22c55e", emoji: "🏥" },
  { id: "dentists", name: "Dentists", file: "/data/dentists.geojson", color: "#06b6d4", emoji: "🦷" },
  { id: "coworking", name: "Coworking", file: "/data/coworking.geojson", color: "#3b82f6", emoji: "💻" },
  { id: "schools", name: "Schools", file: "/data/schools.geojson", color: "#f59e0b", emoji: "🏫" },
];

/** POI ids with very large marker counts; UI warns before enabling (map can freeze while rendering). */
export const HEAVY_POI_LAYER_IDS = new Set(["bike-parking", "restaurants"]);

export const CHOROPLETH_LAYERS = [
  {
    id: "crime-current",
    name: "Crime (Current)",
    file: "/data/crime.json",
    property: "value",
    emoji: "🚨",
    unit: "monthly crimes",
    colorStops: ["#fff5f0", "#fdcab5", "#fc8d6a", "#e7442e", "#a50f15", "#67000d"],
    format: (v) => `${v}`,
    inverse: true,
    tip: "Monthly street-level crime count per LSOA from data.police.uk. Darker = more crimes reported. Covers theft, violence, anti-social behaviour, etc.",
  },
  {
    id: "air",
    name: "Air Quality (NO₂)",
    file: "/data/air-quality.json",
    property: "value",
    emoji: "🌫️",
    unit: "µg/m³",
    colorStops: ["#f0f9e8", "#bae4bc", "#7bccc4", "#f4a460", "#d95f0e", "#8b4513"],
    format: (v) => `${v}`,
    inverse: true,
    tip: "Nitrogen dioxide concentration (µg/m³) interpolated from London Air Quality Network monitors. Higher values mean worse air quality, often near busy roads.",
  },
  {
    id: "rent-est",
    name: "Est. rent (£/mo)",
    file: "/data/rent.json",
    property: "value",
    emoji: "🏘️",
    unit: "modelled £/mo",
    colorStops: ["#f7fcf0", "#e0f3db", "#ccebc5", "#a8ddb5", "#4eb3d3", "#2b8cbe", "#08589e"],
    format: (v) => `£${v}`,
    inverse: true,
    tip: "Indicative 1-bed-style monthly rent (£) modelled from IoD2025 deprivation data and borough anchor rents — not live market data. Useful for relative comparison across areas.",
  },
  {
    id: "house-prices",
    name: "House prices (£)",
    file: "/data/house-prices.json",
    property: "value",
    emoji: "🏠",
    unit: "median sale £",
    colorStops: ["#fff7ec", "#fee8c8", "#fdd49e", "#fdbb84", "#fc8d59", "#e34a33", "#b30000"],
    format: (v) => (v >= 1e6 ? `£${(v / 1e6).toFixed(2).replace(/\.?0+$/, "")}M` : `£${Math.round(v / 1000)}k`),
    inverse: true,
    tip: "Median price paid for residential sales in the LSOA (ONS HPSSA dataset 46 / HM Land Registry, year ending Mar 2023 — the last published edition). Areas with too few sales use a recent earlier year or the borough median.",
  },
  {
    id: "imd",
    name: "Deprivation (Overall)",
    file: "/data/imd.json",
    property: "imd",
    emoji: "📊",
    unit: "IMD score",
    colorStops: ["#f7fcf5", "#c7e9c0", "#74c476", "#fd8d3c", "#e6550d", "#a63603"],
    format: (v) => `${v}`,
    inverse: true,
    tip: "Index of Multiple Deprivation 2025 (MHCLG IoD2025). Combines income, employment, education, health, crime, housing and environment into one score. Higher = more deprived.",
  },
  {
    id: "imd-income",
    name: "Income Deprivation",
    file: "/data/imd.json",
    property: "income",
    emoji: "💰",
    unit: "rate",
    colorStops: ["#f7fbff", "#c6dbef", "#6baed6", "#3182bd", "#08519c", "#08306b"],
    format: (v) => `${(v * 100).toFixed(0)}%`,
    inverse: true,
    tip: "IMD Income domain — proportion of the population experiencing deprivation relating to low income (benefits, tax credits). Higher % = more income-deprived.",
  },
  {
    id: "imd-employment",
    name: "Employment Deprivation",
    file: "/data/imd.json",
    property: "employment",
    emoji: "💼",
    unit: "rate",
    colorStops: ["#fff5eb", "#fdd0a2", "#fdae6b", "#f16913", "#d94801", "#8c2d04"],
    format: (v) => `${(v * 100).toFixed(0)}%`,
    inverse: true,
    tip: "IMD Employment domain — proportion of the working-age population involuntarily excluded from the labour market (unemployment, incapacity). Higher % = more deprived.",
  },
  {
    id: "imd-education",
    name: "Education Deprivation",
    file: "/data/imd.json",
    property: "education",
    emoji: "🎓",
    unit: "score",
    colorStops: ["#f7fcfd", "#ccece6", "#66c2a4", "#41ae76", "#238b45", "#005824"],
    format: (v) => `${v.toFixed(1)}`,
    inverse: true,
    tip: "IMD Education, Skills & Training domain. Measures lack of qualifications and school performance in the area. Higher score = more educationally deprived.",
  },
  {
    id: "imd-health",
    name: "Health Deprivation",
    file: "/data/imd.json",
    property: "health",
    emoji: "🏥",
    unit: "score",
    colorStops: ["#f7fcfd", "#d0d1e6", "#a6bddb", "#74a9cf", "#2b8cbe", "#045a8d"],
    format: (v) => `${v.toFixed(1)}`,
    inverse: true,
    tip: "IMD Health Deprivation & Disability domain. Measures risk of premature death and impairment of quality of life through poor physical or mental health. Higher = worse.",
  },
  {
    id: "imd-crime",
    name: "Crime (IoD2025)",
    file: "/data/imd.json",
    property: "crime",
    emoji: "🔒",
    unit: "score",
    colorStops: ["#fff5f0", "#fdcab5", "#fc8d6a", "#e7442e", "#a50f15", "#67000d"],
    format: (v) => `${v.toFixed(1)}`,
    inverse: true,
    tip: "IMD Crime domain (IoD2025). Measures risk of personal and material victimisation at the local level. Higher score = higher crime risk. See also Crime (Current) for latest data.",
  },
  {
    id: "imd-barriers",
    name: "Housing Barriers",
    file: "/data/imd.json",
    property: "barriers",
    emoji: "🏠",
    unit: "score",
    colorStops: ["#f2f0f7", "#cbc9e2", "#9e9ac8", "#756bb1", "#54278f", "#3f007d"],
    format: (v) => `${v.toFixed(1)}`,
    inverse: true,
    tip: "IMD Barriers to Housing & Services domain. Measures physical and financial accessibility of housing and key local services (e.g. GP, post office). Higher = harder to access.",
  },
  {
    id: "imd-living",
    name: "Living Environment",
    file: "/data/imd.json",
    property: "living",
    emoji: "🌍",
    unit: "score",
    colorStops: ["#ffffcc", "#d9f0a3", "#addd8e", "#78c679", "#31a354", "#006837"],
    format: (v) => `${v.toFixed(1)}`,
    inverse: true,
    tip: "IMD Living Environment domain. Measures quality of indoor (housing condition) and outdoor (air quality, road traffic accidents) local environment. Higher = worse living conditions.",
  },
  {
    id: "pop-density",
    name: "Population Density",
    file: "/data/population-density.json",
    property: "value",
    emoji: "👥",
    unit: "persons/km²",
    colorStops: ["#f7fbff", "#c6dbef", "#6baed6", "#3182bd", "#08519c", "#08306b"],
    format: (v) => v.toLocaleString(),
    inverse: true,
    tip: "Population density (persons per km²) from Census 2021. Darker areas have more people packed in. Central London LSOAs can exceed 20,000/km².",
  },
  {
    id: "ptal",
    name: "PTAL (Transport)",
    file: "/data/ptal.json",
    property: "value",
    emoji: "🚌",
    unit: "access index",
    colorStops: ["#f7fcf5", "#c7e9c0", "#74c476", "#31a354", "#006d2c", "#00441b"],
    format: (v) => (typeof v === "number" ? v.toFixed(1) : String(v ?? "")),
    inverse: false,
    tip: "TfL Public Transport Accessibility Level — mean access index per LSOA (2023). Higher = better connected by bus, tube, rail, tram and DLR. Darker = more accessible.",
  },
  {
    id: "green-space",
    name: "Green Space",
    file: "/data/green-space.json",
    property: "value",
    emoji: "🌿",
    unit: "score",
    colorStops: ["#fff7ec", "#d9f0a3", "#addd8e", "#78c679", "#31a354", "#006837"],
    format: (v) => `${v}`,
    inverse: false,
    tip: "Green space density score from OpenStreetMap parks and gardens near each LSOA (see scrapers/green-space.js). Higher score = more green space nearby; darker greens on the map = more green space.",
  },
  {
    id: "noise",
    name: "Noise (Lden)",
    file: "/data/noise.json",
    property: "value",
    emoji: "🔊",
    unit: "dB",
    colorStops: ["#f7fcf0", "#d9f0a3", "#fdae6b", "#f16913", "#d94801", "#8c2d04"],
    format: (v) => `${v} dB`,
    inverse: true,
    tip: "Day-evening-night noise level (Lden, dB) from Defra strategic noise mapping, interpolated to LSOAs. Higher = louder; busy roads and flight paths dominate. Lower is generally better for sleep and health.",
  },
  {
    id: "flood-risk",
    name: "Flood risk (Zone 3)",
    file: "/data/flood-risk.json",
    property: "value",
    emoji: "🌊",
    unit: "% of area",
    colorStops: ["#f0f7ff", "#c6dbef", "#9ecae1", "#6baed6", "#3182bd", "#08519c"],
    format: (v) => `${v}%`,
    inverse: true,
    tip: "Share of the area inside Environment Agency Flood Zone 3 — land with a 1-in-100 (river) or 1-in-200 (sea) yearly flood chance, ignoring defences such as the Thames Barrier. Higher = more of the neighbourhood sits on the undefended floodplain.",
  },
  {
    id: "broadband",
    name: "Gigabit Broadband",
    file: "/data/broadband.json",
    property: "value",
    emoji: "📡",
    unit: "% premises",
    colorStops: ["#f7fbff", "#c6dbef", "#9ecae1", "#6baed6", "#3182bd", "#08519c"],
    format: (v) => (typeof v === "number" ? `${v.toFixed(1)}%` : String(v ?? "")),
    inverse: false,
    tip: "Share of premises that can order gigabit-capable fixed broadband (Ofcom Connected Nations 2025, July 2025 snapshot), summed from output areas to each LSOA. Darker = more premises with gigabit available.",
  },
];

/**
 * Area filter sliders. mode "max": LSOA passes when raw ≤ threshold. mode "min": passes when raw ≥ threshold.
 * Threshold keys match `CHOROPLETH_LAYERS` ids (URL hash `f` JSON).
 */
export const FILTER_CHOROPLETH_DIMS = [
  { id: "crime-current", label: "Max Crime Score", mode: "max", min: 0, max: 200, step: 1 },
  { id: "air", label: "Max NO\u2082 (\u00b5g/m\u00b3)", mode: "max", min: 0, max: 80, step: 1 },
  { id: "house-prices", label: "Max median house price (\u00a3)", mode: "max", min: 200000, max: 2000000, step: 10000 },
  { id: "imd", label: "Max Deprivation", mode: "max", min: 0, max: 60, step: 1 },
  { id: "pop-density", label: "Max population density (per km\u00b2)", mode: "max", min: 0, max: 25000, step: 100 },
  { id: "noise", label: "Max noise (Lden dB)", mode: "max", min: 40, max: 80, step: 1 },
  { id: "ptal", label: "Min access index", mode: "min", min: 0, max: 100, step: 1 },
  { id: "green-space", label: "Min green space score", mode: "min", min: 0, max: 100, step: 1 },
  { id: "flood-risk", label: "Max flood zone 3 (%)", mode: "max", min: 0, max: 100, step: 5 },
  { id: "broadband", label: "Min gigabit availability (%)", mode: "min", min: 0, max: 100, step: 5 },
];

export const TRANSIT_RINGS = [
  { mins: 15, opacity: 0.20 },
  { mins: 30, opacity: 0.12 },
  { mins: 45, opacity: 0.06 },
];

export const TRANSIT_COLORS = [
  "#3b82f6", "#e040fb", "#00bcd4", "#ff9800", "#8bc34a", "#f44336",
];

export const WALK_RINGS = [
  { mins: 5, meters: 400, color: "#ff3366", opacity: 0.18 },
  { mins: 15, meters: 1200, color: "#ff3366", opacity: 0.13 },
  { mins: 30, meters: 2400, color: "#ff3366", opacity: 0.09 },
  { mins: 45, meters: 3600, color: "#ff3366", opacity: 0.055 },
];

export const SCORE_AREA_DIMS = [
  { id: "crime-current", label: "Low Crime", property: "value", tip: "Monthly street-level crimes from data.police.uk. Scored by inverse percentile across all London LSOAs \u2014 fewer crimes = higher score." },
  { id: "air", label: "Clean Air", property: "value", tip: "NO\u2082 concentration (\u00b5g/m\u00b3) interpolated from London Air Quality Network monitoring stations. Lower pollution = higher score." },
  { id: "house-prices", label: "Affordable to buy", property: "value", tip: "Median residential sale price (\u00a3) in the LSOA, year ending Mar 2023, from ONS HPSSA dataset 46 (HM Land Registry price paid). Lower \u00a3 = higher score." },
  { id: "imd", label: "Low Deprivation", property: "imd", tip: "Overall Index of Multiple Deprivation (IoD2025) from MHCLG. Combines income, employment, education, health, crime, housing & environment. Lower deprivation = higher score." },
  { id: "imd-income", label: "Income", property: "income", tip: "IMD Income Deprivation rate \u2014 proportion of the population experiencing deprivation relating to low income. Lower rate = higher score." },
  { id: "imd-education", label: "Education", property: "education", tip: "IMD Education, Skills & Training score. Measures lack of attainment and skills in the local population. Lower deprivation = higher score." },
  { id: "imd-health", label: "Health", property: "health", tip: "IMD Health Deprivation & Disability score. Measures risk of premature death and impairment of quality of life through poor health. Lower = higher score." },
  { id: "imd-barriers", label: "Housing Access", property: "barriers", tip: "IMD Barriers to Housing & Services score. Measures physical and financial accessibility of housing and local services. Lower barriers = higher score." },
  { id: "imd-living", label: "Living Env.", property: "living", tip: "IMD Living Environment score. Measures quality of the indoor and outdoor local environment (housing condition, air quality, road traffic accidents). Lower = higher score." },
  { id: "pop-density", label: "Low Density", property: "value", tip: "Population density (persons/km\u00b2) from Census 2021. Lower density = higher score." },
  { id: "ptal", label: "Transport", property: "value", inverse: false, tip: "TfL 2023 LSOA mean access index (AI) — numeric input to PTAL bands. Higher = better public transport access = higher score." },
  { id: "green-space", label: "Green Space", property: "value", inverse: false, tip: "Green space density score derived from OpenStreetMap parks and gardens near each LSOA. Higher = more green space nearby = higher score." },
  { id: "noise", label: "Low Noise", property: "value", tip: "Noise levels (Lden dB) interpolated from Defra noise mapping data. Lower noise = higher score." },
  { id: "flood-risk", label: "Low flood risk", property: "value", tip: "% of the LSOA inside EA Flood Zone 3 (undefended 1-in-100 river / 1-in-200 sea). Less floodplain = higher score." },
  { id: "broadband", label: "Fast broadband", property: "value", inverse: false, tip: "% of premises with gigabit-capable broadband available (Ofcom Connected Nations 2025). Higher availability = higher score." },
];

export const SCORE_PROX_DIMS = [
  { id: "tube", label: "Tube/Rail", pointLayer: "tube", cap: 8, tip: "Density-weighted score for nearby Tube/Rail stations. Rewards multiple stations within walking distance. More stations closer = higher score." },
  { id: "waitrose", label: "Waitrose", pointLayer: "waitrose", cap: 3, tip: "Density-weighted score for nearby Waitrose stores. Rewards having options, not just one far away." },
  { id: "supermarkets", label: "Supermarkets", pointLayer: "supermarkets", cap: 6, tip: "Density-weighted score for nearby supermarkets of any brand (OpenStreetMap shop=supermarket). Several within walking distance = higher score." },
  { id: "coffee", label: "Coffee", pointLayer: "coffee", cap: 12, tip: "Density-weighted score for nearby coffee shops. Rewards areas with a good selection within walking distance." },
  { id: "libraries", label: "Libraries", pointLayer: "libraries", cap: 6, tip: "Density-weighted score for nearby public libraries (OpenStreetMap). More branches within walking distance = higher score." },
  { id: "pubs", label: "Pubs", pointLayer: "pubs", cap: 15, tip: "Density-weighted score for nearby pubs. Rewards areas with good pub density." },
  { id: "parks", label: "Parks", pointLayer: "parks", cap: 5, tip: "Density-weighted score for nearby parks and gardens. Multiple green spaces nearby = higher score." },
  { id: "yoga", label: "Yoga", pointLayer: "yoga", cap: 4, tip: "Density-weighted score for nearby yoga studios. Rewards areas with good studio density." },
  { id: "gyms", label: "Gym", pointLayer: "gyms", cap: 6, tip: "Density-weighted score for nearby gyms/fitness centres. Rewards having several options to choose from." },
  { id: "cinemas", label: "Cinemas", pointLayer: "cinemas", cap: 3, tip: "Density-weighted score for nearby cinemas. Rewards having options within reach." },
  { id: "bike-parking", label: "Bike Parking", pointLayer: "bike-parking", cap: 30, tip: "Density-weighted score for nearby bicycle parking. Very abundant in London; needs high density to score well." },
  { id: "betting", label: "No Betting", pointLayer: "betting", inverse: true, cap: 4, tip: "Inverse density score \u2014 more betting shops nearby = lower score. Areas with none nearby score 100." },
  { id: "restaurants", label: "Restaurants", pointLayer: "restaurants", cap: 20, tip: "Density-weighted score for nearby restaurants. Rewards areas with a good selection within walking distance." },
  { id: "gp-surgeries", label: "GP Surgery", pointLayer: "gp-surgeries", cap: 3, tip: "Density-weighted score for nearby GP surgeries. Having options nearby = higher score." },
  { id: "dentists", label: "Dentist", pointLayer: "dentists", cap: 3, tip: "Density-weighted score for nearby dental practices (OpenStreetMap). Having options nearby = higher score." },
  { id: "coworking", label: "Coworking", pointLayer: "coworking", cap: 4, tip: "Density-weighted score for nearby coworking spaces. More options = higher score." },
  { id: "schools", label: "Schools", pointLayer: "schools", cap: 6, tip: "Density-weighted score for nearby schools (DfE GIAS, all phases incl. independent). Several within walking distance = higher score; each pin shows the latest Ofsted outcome." },
];
